### ISSUE TITLE
Export the `transform` function to work directly with the tree

### ISSUE THREAD

**Issue by ooker777** [jake-low/remark-sectionize#13]
Would you think that it's a good idea to make this as an extension for the transformer only? That would make the code more cleaner for those who don't need to stringify to text.

**Comment by jake-low** [comment]
This module's default export is a function which returns a transformer, which I think is the standard convention for remark plugins. You can call this function to get the `transform` function and use it directly if you wish.

```js
const plugin = requrie("remark-sectionize");
const transform = plugin(); // transform is now the same transform function from this project's index.js
transform(someTree); // calling it on a parsed markdown syntax tree will mutate that tree
```

Let me know if I've misunderstood your request or if this doesn't address your use case.

**Comment by ooker777** [comment]
Ah, good trick. Glad to know that. Thanks
